### ISSUE TITLE
Uncaught runtime exception - property not found

### ISSUE THREAD

**Issue by christopher-keith** [Unicon/shib-mfa-duo-auth#16]
I am attempting to upgrade our IDPs at Brown University.  I followed @langedb  configuration from the Shib wiki and arrived at a functional configuration under version 1.0.1 of the shib-mfa-duo-auth.  I then attempted to add a custom duo-authn-flow.xml definition because I need to pass additional data to the velocity template for Duo.  I upgraded to 1.1.3 and started receiving the following.  I then downgraded to 1.1.2 and still received the following error.  I was going to try 1.1.1 but I was not able to build that version locally and didn't see it available pre-built for download.

`2016-07-06 14:05:51,318 - INFO [net.unicon.iam.shibboleth.idp.authn.duo.authn.ValidateDuoResponse:-2] - Profile Action ValidateDuoResponse: Duo Login succeeded
2016-07-06 14:05:51,322 - DEBUG [net.shibboleth.idp.authn.AbstractValidationAction:311] - Profile Action ValidateDuoResponse: Adding custom Principal(s) defined on underlying flow descriptor
2016-07-06 14:05:51,330 - ERROR [net.shibboleth.idp.authn:-2] - Uncaught runtime exception
org.springframework.binding.expression.PropertyNotFoundException: Property not found
    at org.springframework.binding.expression.spel.SpringELExpression.getValue(SpringELExpression.java:87)
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1008E:(pos 0): Property or field 'UpdateSessionWithAuthenticationResult' cannot be found on object of type 'org.springframework.webflow.engine.impl.RequestControlContextImpl' - maybe not public?
    at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:224)`

**Comment by scalding** [comment]
Could you try the latest master? There was a shift in how things are configured. Thanks

**Comment by christopher-keith** [comment]
I would be happy to but I am unable to build from source.  When following the readme, I get the following when trying to build:

FAILURE: Build failed with an exception.
- Where:
  Build file '/Users/ckeith/LocalGit/Unicon/shib-mfa-duo-auth/build.gradle' line: 84
- What went wrong:
  A problem occurred evaluating root project 'shibboleth-duo-auth'.
  
  > Could not find property 'bintrayUsername' on task ':uploadDist'.

**Comment by scalding** [comment]
okay, looks like I was missing a couple properties used for deploying the artifact. Could you try building now? Thanks

**Comment by christopher-keith** [comment]
Thanks.  Build worked fine for 1.1.4-Snapshot.  After installing, I ultimately discovered that the error I was seeing was caused by the customizations I was attempting to make to duo.vm.
